### ISSUE TITLE
Still calling to backend after the validation of client returns false. 

### ISSUE THREAD

**Issue by yeungon** [vietspeak/VietSpeakWebsite#11]
![Screenshot from 2022-01-26 10-43-39](https://user-images.githubusercontent.com/3062418/151100528-a32cc4bf-1fb6-447c-b809-4c97a41e3e9e.png)

I am going to make a PR to address this issue.

**Comment by dvbui** [comment]
Thank you. I'll try to do more pre-check on client's machine in the future.
